version: "3.3"

services:
  post-service-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'post_service_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'sa'
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_TCP_PORT: 3306

  comment-service-db:
    image: mysql:latest
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: 'comment_service_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'sa'
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_TCP_PORT: 3307

  review-service-db:
    image: mysql:latest
    ports:
      - "3308:3308"
    environment:
      MYSQL_DATABASE: 'review_service_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'sa'
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_TCP_PORT: 3308

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ broker port
      - "15672:15672" # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password